### ISSUE TITLE
steering angle error

### ISSUE THREAD

**Issue by ahuazuipiaoliang** [pixmoving-moveit/pix_driver#8]
`steering_tire_angle` of `/vehicle/status/steering_status` is always 0.0
```
stamp:
  sec: 1678873613
  nanosec: 817495252
steering_tire_angle: -0.0
```
